sstu-nevdev/Controllers/AuditController.cs
using Domain.Core.Logs;
using PagedList;
using Service.Interfaces;
using sstu_nevdev.App_Start;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace sstu_nevdev.Controllers
{
    [Authorize(Roles = "SSTU_Administrator")]
    public class AuditController : Controller
    {
        IAuditService service;

        public AuditController(IAuditService service)
        {
            this.service = service;
        }

        public ActionResult Index(int? page)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(service.GetAll().OrderByDescending(x => x.ModifiedDate)
                .ToPagedList(pageNumber, pageSize));
        }

        [HttpPost]
        public ActionResult Index(string query, int? page)
        {
            ViewBag.Query = query;
            string[] parsedQuery = query.Split(null);
            List<Audit> result = new List<Audit>();
            foreach (var item in service.GetAll())
            {
                foreach (var value in parsedQuery)
                {
                    if (Comparator.PropertiesThatContainText(item, value))
                    {
                        result.Add(item);
                        break;
                    }
                }
            }
            int pageSize = 50;
            int pageNumber = (page ?? 1);
            return View(result.OrderBy(x => x.ModifiedDate).ToPagedList(pageNumber, pageSize));
        }
    }
}

sstu-nevdev/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SSTU-Security</title>
    <link rel="shortcut icon" type="image/ico" href="@Url.Content("~/Content/assets/favicon.ico")">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top header">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("SSTU", "Index", "Home", new { area = "" }, new { @class = "navbar-brand layout-font" })
            </div>
            <div class="navbar-collapse collapse nav-height">
                @if (User.Identity.IsAuthenticated && User.IsInRole("SSTU_Administrator"))
                {
                    <ul class="menu nav navbar-nav">
                        <li>@Html.ActionLink("Датчики", "Index", "Checkpoint")</li>
                        <li>@Html.ActionLink("Пользователи", "Index", "Identity")</li>
                        <li>@Html.ActionLink("События", "Index", "Activity")</li>
                        <li>@Html.ActionLink("Журнал", "Index", "Audit")</li>
                        <li>@Html.ActionLink("БД", "Index", "Database")</li>
                        <li>@Html.ActionLink("API", "", "Swagger")</li>
                        <li>@Html.ActionLink("Задания", "", "Hangfire")</li>
                    </ul>
                }
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content body-margin">
        @RenderBody()

        <div class="navbar-inverse navbar-fixed-bottom">
            <footer>
                <div class="footer-text">
                    &copy; @DateTime.Now.Year - <a href="mailto:geerkus@gmail.com">nevdev</a>
                </div>
            </footer>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/site")
    @RenderSection("scripts", required: false)
</body>
</html>